name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - name: Run the static analysis and test
      run: |
        gem install bundler -v 2.2.3
        bundle install
        bundle exec rubocop
        sudo apt-get install libsqlite3-dev
        cd test/dummy && rails db:test:prepare && rails db:migrate
        bundle exec rails test